begin;

-- Provision only derived/generated scheduler material. No secret value is
-- embedded in source control: the publishable key is copied inside Vault and
-- the internal token is generated by Postgres.
do $$
declare
  existing_publishable_key text;
  billing_url text;
begin
  if not exists (
    select 1 from vault.secrets
    where name = 'app_monthly_billing_internal_token'
  ) then
    perform vault.create_secret(
      encode(gen_random_bytes(32), 'hex'),
      'app_monthly_billing_internal_token',
      'Token interno gerado para cron de mensalidades do Ilha Play'
    );
  end if;

  select secret.decrypted_secret
    into billing_url
  from vault.decrypted_secrets as secret
  where secret.name = 'app_monthly_billing_url'
  limit 1;

  if billing_url is null then
    select pg_catalog.regexp_replace(
      secret.decrypted_secret,
      '/tournament-payment-expiry$',
      '/app-monthly-billing'
    )
      into billing_url
    from vault.decrypted_secrets as secret
    where secret.name = 'tournament_payment_expiry_url'
      and secret.decrypted_secret ~
        '^https://[a-z0-9]{20}[.]supabase[.]co/functions/v1/tournament-payment-expiry$'
    limit 1;

    if billing_url is not null
       and encode(
         extensions.digest(pg_catalog.convert_to(billing_url, 'UTF8'), 'sha256'),
         'hex'
       ) = 'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b' then
      perform vault.create_secret(
        billing_url,
        'app_monthly_billing_url',
        'URL derivada da rotina de torneios para mensalidades do mesmo projeto'
      );
    end if;
  end if;

  if billing_url ~
       '^https://[a-z0-9]{20}[.]supabase[.]co/functions/v1/app-monthly-billing$'
     and encode(
       extensions.digest(pg_catalog.convert_to(billing_url, 'UTF8'), 'sha256'),
       'hex'
     ) = 'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b'
     and not exists (
       select 1 from vault.secrets
       where name = 'app_monthly_billing_url_sha256'
     ) then
    perform vault.create_secret(
      'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b',
      'app_monthly_billing_url_sha256',
      'Hash fixado da URL mensal para impedir redirecionamento do cron'
    );
  end if;

  if not exists (
    select 1 from vault.secrets
    where name = 'app_monthly_billing_publishable_key'
  ) then
    select secret.decrypted_secret
      into existing_publishable_key
    from vault.decrypted_secrets as secret
    where secret.name = 'tournament_payment_expiry_publishable_key'
    limit 1;

    if existing_publishable_key ~ '^sb_publishable_[A-Za-z0-9_-]{20,}$' then
      perform vault.create_secret(
        existing_publishable_key,
        'app_monthly_billing_publishable_key',
        'Chave publicável reutilizada pelo cron de mensalidades do Ilha Play'
      );
    end if;
  end if;
end;
$$;

create or replace function public.verify_app_monthly_billing_internal_token(
  p_token text
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  stored_token text;
begin
  if coalesce((select auth.jwt() ->> 'role'), '') <> 'service_role' then
    raise exception 'Esta operação exige a função de serviço.' using errcode = '42501';
  end if;
  if length(coalesce(p_token, '')) < 32 then
    return false;
  end if;

  select secret.decrypted_secret
    into stored_token
  from vault.decrypted_secrets as secret
  where secret.name = 'app_monthly_billing_internal_token'
  limit 1;

  return stored_token is not null
    and extensions.digest(
      pg_catalog.convert_to(p_token, 'UTF8'),
      'sha256'
    ) = extensions.digest(
      pg_catalog.convert_to(stored_token, 'UTF8'),
      'sha256'
    );
end;
$$;

revoke all on function public.verify_app_monthly_billing_internal_token(text)
  from public, anon, authenticated, service_role;
grant execute on function public.verify_app_monthly_billing_internal_token(text)
  to service_role;

create or replace function private.invoke_app_monthly_billing_action(p_action text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  billing_url text;
  billing_url_sha256 text;
  publishable_key text;
  internal_token text;
begin
  if p_action not in ('scheduled', 'reconcile') then
    raise exception 'A ação interna de cobrança mensal é inválida.'
      using errcode = '22023';
  end if;

  select secret.decrypted_secret
    into billing_url
  from vault.decrypted_secrets as secret
  where secret.name = 'app_monthly_billing_url'
  limit 1;

  select secret.decrypted_secret
    into publishable_key
  from vault.decrypted_secrets as secret
  where secret.name = 'app_monthly_billing_publishable_key'
  limit 1;

  select secret.decrypted_secret
    into billing_url_sha256
  from vault.decrypted_secrets as secret
  where secret.name = 'app_monthly_billing_url_sha256'
  limit 1;

  select secret.decrypted_secret
    into internal_token
  from vault.decrypted_secrets as secret
  where secret.name = 'app_monthly_billing_internal_token'
  limit 1;

  if billing_url is null
     or billing_url_sha256 is null
     or billing_url !~
       '^https://[a-z0-9]{20}[.]supabase[.]co/functions/v1/app-monthly-billing$'
     or billing_url_sha256 !~ '^[0-9a-f]{64}$'
     or billing_url_sha256 <>
       'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b'
     or encode(
       extensions.digest(pg_catalog.convert_to(billing_url, 'UTF8'), 'sha256'),
       'hex'
     ) <> 'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b'
     or publishable_key is null
     or publishable_key !~ '^sb_publishable_[A-Za-z0-9_-]{20,}$'
     or internal_token is null
     or length(internal_token) < 32 then
    raise exception 'O agendamento mensal não possui configuração segura no Vault.'
      using errcode = '55000';
  end if;

  return net.http_post(
    url := billing_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', publishable_key,
      'x-monthly-billing-token', internal_token
    ),
    body := jsonb_build_object('action', p_action),
    timeout_milliseconds := 120000
  );
end;
$$;

revoke all on function private.invoke_app_monthly_billing_action(text)
  from public, anon, authenticated, service_role;

create or replace function public.invoke_app_monthly_billing()
returns bigint
language sql
security definer
set search_path = ''
as $$
  select private.invoke_app_monthly_billing_action('scheduled')
$$;

revoke all on function public.invoke_app_monthly_billing()
  from public, anon, authenticated, service_role;
grant execute on function public.invoke_app_monthly_billing() to service_role;

create or replace function public.reconcile_app_monthly_billing()
returns bigint
language sql
security definer
set search_path = ''
as $$
  select private.invoke_app_monthly_billing_action('reconcile')
$$;

revoke all on function public.reconcile_app_monthly_billing()
  from public, anon, authenticated, service_role;
grant execute on function public.reconcile_app_monthly_billing() to service_role;

do $$
declare
  job_id bigint;
begin
  for job_id in
    select job.jobid
    from cron.job as job
    where job.jobname in (
      'ilha-play-generate-monthly-pix',
      'ilha-play-reconcile-monthly-pix'
    )
  loop
    perform cron.unschedule(job_id);
  end loop;
end;
$$;

-- Only the official production URL is scheduled. Local/staging databases do
-- not inherit a production destination and remain inactive.
do $$
declare
  billing_url text;
  billing_url_sha256 text;
  publishable_key text;
  internal_token text;
begin
  select secret.decrypted_secret into billing_url
    from vault.decrypted_secrets as secret
   where secret.name = 'app_monthly_billing_url'
   limit 1;
  select secret.decrypted_secret into publishable_key
    from vault.decrypted_secrets as secret
   where secret.name = 'app_monthly_billing_publishable_key'
   limit 1;
  select secret.decrypted_secret into billing_url_sha256
    from vault.decrypted_secrets as secret
   where secret.name = 'app_monthly_billing_url_sha256'
   limit 1;
  select secret.decrypted_secret into internal_token
    from vault.decrypted_secrets as secret
   where secret.name = 'app_monthly_billing_internal_token'
   limit 1;

  if billing_url is not null
     and encode(
       extensions.digest(pg_catalog.convert_to(billing_url, 'UTF8'), 'sha256'),
       'hex'
     ) = 'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b'
     and billing_url_sha256 =
       'aae011373696cd3246639fdd0b5c1dbe7dc9c3a5473fdc7920875100c08f547b'
     and publishable_key ~ '^sb_publishable_[A-Za-z0-9_-]{20,}$'
     and length(coalesce(internal_token, '')) >= 32 then
    -- pg_cron uses UTC. 12:05 UTC is 09:05 in America/Sao_Paulo.
    perform cron.schedule(
      'ilha-play-generate-monthly-pix',
      '5 12 * * *',
      $cron$select public.invoke_app_monthly_billing();$cron$
    );

    -- Polling is independent from generation and never claims READY/FAILED.
    perform cron.schedule(
      'ilha-play-reconcile-monthly-pix',
      '*/15 * * * *',
      $cron$select public.reconcile_app_monthly_billing();$cron$
    );
  end if;
end;
$$;

commit;
